### ISSUE TITLE
not installing in python3

### ISSUE THREAD

**Issue by ttm** [RDFLib/rdflib-web#6]
r@K45VM:~/repos/rdflib-web$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    config.update({'src_root': setup_python3()})
  File "setup.py", line 15, in setup_python3
    for line in open("MANIFEST.in"):
FileNotFoundError: [Errno 2] No such file or directory: 'MANIFEST.in'

I commented line 66 (dummy me). And now the error I get (with either install or uninstall commands) is:

r@K45VM:~/repos/rdflib-web$ sudo python3 setup.py uninstall
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python3.4/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

**Comment by ttm** [comment]
restored packaging system with:
$ rm `python -c "import pkg_resources; print(pkg_resources.__file__)"`

**Comment by white-gecko** [comment]
I get:

```
$ pip install rdflib-web
Collecting rdflib-web
  Could not find a version that satisfies the requirement rdflib-web (from versions: )
No matching distribution found for rdflib-web

```

**Comment by gromgull** [comment]
This project is pretty much abandoned. It was created before rdflib worked with python3 (or before I did). It shouldn't be rocket science to make it work in py3, but I will not do it.

**Comment by gromgull** [comment]
By _this project_, I mean `rdflib-web` - the rest of rdflib is quite alive!

**Comment by gromgull** [comment]
This was also made quite a few years back - web-dev technology has come quite far since then, I would redo this as a single page app if I were to redo it today.

**Comment by white-gecko** [comment]
Cool, thanks for the clarification.

**Comment by rwst** [comment]
So which open source solution would a newbie like me choose for setting up a SPARQL web endpoint for a few hundred RDF graphs?

**Comment by dotmpe** [comment]
I found a partial python3 port at the Y-Digital clone. I made it run with the flask dev server as well. Maybe there is an issue with encoding but initial impression is that it installs and runs well.
```
pip3 install https://github.com/dotmpe/rdflib-web/archive/master.zip
```

May offer for PR at later time.
